env:
  es2021: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
        "semi": ["error", "always"],
        "quotes": ["error", "double"],
        "allow": ["warn", "error"]
        "no-restricted-imports": ["error", "import1", "import2"]
}
